server:
  port: 8080

spring:
  application:
    name: toxin-backend

  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_HOST:localhost}:5432/database
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: 6379

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml


